package tn.steg.backend.document.domain.model;

public enum DocumentType {
    CV,
    MOTIVATION_LETTER,
    UNIVERSITY_CONVENTION,
    TRANSCRIPT,
    INTERNSHIP_APPLICATION,
    ASSIGNMENT_LETTER,
    INTERNSHIP_CONVENTION,
    STEG_INTERNSHIP_REPORT,
    CAHIER_DES_CHARGES,
    PROJECT_DEMO_IMAGE,
    INTERNSHIP_CERTIFICATE,
    INTERNSHIP_LOGBOOK,
    CIN_COPY,
    PAYMENT_RECEIPT,
    OTHER
}
