package tn.steg.backend.companion.interfaces.rest;

import com.fasterxml.jackson.databind.JsonNode;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.context.annotation.Import;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.web.servlet.MvcResult;
import tn.steg.backend.TestcontainersConfiguration;
import tn.steg.backend.testsupport.FakeAiCompletionClientConfiguration;

import java.time.LocalDate;
import java.time.ZoneId;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * T09/B6 + BR-33 (interim identity rule, D4b/B8 stay T10's decision): the
 * generated journal is a deliverable of the internship marked by a
 * deterministic title, regeneration replaces an unsubmitted draft, and a
 * SUBMITTED/VALIDATED journal is immutable — a new draft is created instead
 * (ST-JRN-06 + the documented edge cases).
 */
@SpringBootTest
@ActiveProfiles("test")
@Import({TestcontainersConfiguration.class, FakeAiCompletionClientConfiguration.class})
@DisplayName("T09/B6 — journal document identity (Testcontainers)")
class JournalDocumentIdentityTest extends JournalTestSupport {

    private static final ZoneId TUNIS = ZoneId.of("Africa/Tunis");

    private Intern eligibleStudent(String tag) {
        LocalDate today = LocalDate.now(TUNIS);
        return createStudent(tag, supervisorUser, today.minusMonths(4), today.plusDays(5));
    }

    private void scriptValid() {
        scriptAi("{\"title\": \"Journal " + run + "\","
                + "\"period\": {\"start\": \"2026-01-01\", \"end\": \"2026-02-01\"},"
                + "\"introduction\": \"Introduction.\", \"summaryByPhase\": [], \"taskTable\": [],"
                + "\"conclusion\": \"Conclusion.\"}");
    }

    private JsonNode generate(Intern intern) throws Exception {
        MvcResult result = postJson("/api/internships/" + intern.internshipId() + "/journal/generate",
                intern.token(), null);
        assertThat(result.getResponse().getStatus()).isEqualTo(201);
        return objectMapper.readTree(result.getResponse().getContentAsString());
    }

    @Test
    @DisplayName("the document is identifiable: marker title, DRAFT, listed with the internship's deliverables")
    void createdDocumentIsIdentifiable() throws Exception {
        Intern intern = eligibleStudent("I");
        scriptValid();

        JsonNode json = generate(intern);
        JsonNode deliverable = json.path("deliverable");
        assertThat(deliverable.path("title").asText())
                .isEqualTo("Journal de stage — " + intern.reference());
        assertThat(deliverable.path("status").asText()).isEqualTo("DRAFT");
        assertThat(deliverable.path("currentVersion").asInt()).isEqualTo(1);
        assertThat(deliverable.path("submittedAt").isNull()).isTrue();
        assertThat(deliverable.path("latestVersion").path("changeSummary").asText())
                .isEqualTo("Generated by the server");
        assertThat(deliverable.path("latestVersion").path("mimeType").asText())
                .isEqualTo("application/pdf");

        MvcResult listed = getJson("/api/internships/" + intern.internshipId() + "/deliverables", intern.token());
        assertThat(listed.getResponse().getStatus()).isEqualTo(200);
        JsonNode content = objectMapper.readTree(listed.getResponse().getContentAsString()).path("content");
        assertThat(content).hasSize(1);
        assertThat(content.path(0).path("id").asText()).isEqualTo(deliverable.path("id").asText());
    }

    @Test
    @DisplayName("regenerating an unsubmitted draft replaces it with a new version of the SAME deliverable")
    void regeneratingReplacesTheDraft() throws Exception {
        Intern intern = eligibleStudent("R");
        scriptValid();

        JsonNode first = generate(intern);
        UUID deliverableId = UUID.fromString(first.path("deliverable").path("id").asText());

        JsonNode second = generate(intern);
        assertThat(second.path("deliverable").path("id").asText()).isEqualTo(deliverableId.toString());
        assertThat(second.path("deliverable").path("currentVersion").asInt()).isEqualTo(2);
        assertThat(second.path("replacedDraft").asBoolean()).isTrue();
        assertThat(second.path("previousSubmitted").asBoolean()).isFalse();
        assertThat(first.path("replacedDraft").asBoolean()).isFalse();

        assertThat(deliverableRepository.findByInternshipId(intern.internshipId())).hasSize(1);
        var versions = deliverableVersionRepository.findByDeliverableIdOrderByVersionNumberAsc(deliverableId);
        assertThat(versions).hasSize(2);
        assertThat(versions.get(1).getVersionNumber()).isEqualTo(2);
        assertThat(versions.get(1).getChangeSummary()).isEqualTo("AI regeneration");
        // The v1 artifact stays readable: versions are kept, never overwritten.
        assertThat(downloadPdfText(deliverableId, intern.token())).contains("Journal " + run);
    }

    @Test
    @DisplayName("a submitted journal is immutable: regeneration creates a NEW draft and tells the student")
    void submittedJournalIsImmutable() throws Exception {
        Intern intern = eligibleStudent("S");
        scriptValid();

        JsonNode first = generate(intern);
        UUID submittedId = UUID.fromString(first.path("deliverable").path("id").asText());
        MvcResult submit = postJson("/api/internships/deliverables/" + submittedId + "/submit",
                intern.token(), null);
        assertThat(submit.getResponse().getStatus()).isEqualTo(200);
        assertThat(objectMapper.readTree(submit.getResponse().getContentAsString())
                .path("status").asText()).isEqualTo("SUBMITTED");

        JsonNode second = generate(intern);
        UUID newDraftId = UUID.fromString(second.path("deliverable").path("id").asText());
        assertThat(newDraftId).isNotEqualTo(submittedId);
        assertThat(second.path("replacedDraft").asBoolean()).isFalse();
        assertThat(second.path("previousSubmitted").asBoolean()).isTrue();
        assertThat(second.path("deliverable").path("title").asText())
                .endsWith(" (nouveau)");
        assertThat(second.path("deliverable").path("status").asText()).isEqualTo("DRAFT");

        // The submitted document is untouched: same status, same single version.
        JsonNode after = objectMapper.readTree(
                getJson("/api/internships/deliverables/" + submittedId, intern.token())
                        .getResponse().getContentAsString());
        assertThat(after.path("status").asText()).isEqualTo("SUBMITTED");
        assertThat(after.path("currentVersion").asInt()).isEqualTo(1);
        assertThat(deliverableVersionRepository
                .findByDeliverableIdOrderByVersionNumberAsc(submittedId)).hasSize(1);

        // A rejected draft is replaceable again (the draft branch of the rule).
        MvcResult reject = postJson("/api/internships/deliverables/" + submittedId + "/reject",
                supervisorToken, "{\"comment\": \"Compléter les tâches\"}");
        assertThat(reject.getResponse().getStatus()).isEqualTo(200);
        JsonNode third = generate(intern);
        assertThat(third.path("deliverable").path("id").asText())
                .isEqualTo(second.path("deliverable").path("id").asText());
        assertThat(third.path("deliverable").path("currentVersion").asInt()).isEqualTo(2);
        assertThat(third.path("replacedDraft").asBoolean()).isTrue();
        assertThat(third.path("previousSubmitted").asBoolean()).isFalse();
    }
}
