/**
 * Server-side official document rendering (Phase A11): swappable wording
 * templates, shared STEG branding, and PDFBox-based PDF generation.
 * Generated bytes are persisted through Phase A6 file storage as FileAsset
 * records — never written back into resources.
 */
package tn.steg.backend.document.infrastructure.pdf;
